name: musicpresence-redirects

networks:
  musicpresence_network:
    external: true

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/confign
    networks:
      - musicpresence_networkk
    hostname: ${COMPOSE_PROJECT_NAME}_caddy

volumes:
  caddy_data:
  caddy_config:
