name: musicpresence-redirects

networks:
  musicpresence_network:
    external: true

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./caddy:/etc/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - musicpresence_network
    hostname: ${COMPOSE_PROJECT_NAME}_caddy

volumes:
  caddy_data:
  caddy_config:
